dotnet test "--logger:junit;LogFilePath=./test-reports/results.xml" /p:Include="[DummyLibrary*]*" /p:Exclude="[*]*AutoGeneratedProgram" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Thereshold=80 /p:CoverletOutput="../Coverage/coverage.xml"

reportgenerator "-reports:../coverage/coverage.xml" "-targetdir:../coverage/" -reporttypes:HTMLInline